export const DataProducts = [
  {
    id: "1",
    galeria: [
      "https://github.com/marlonberaldo.png/",
      "https://github.com/neto18081.png/",
      "https://github.com/victormonteiro.png/",
      "https://github.com/maria.png/",
      "https://github.com/marlonberaldo.png/",
      "https://github.com/neto18081.png/",
      "https://github.com/victormonteiro.png/",
      "https://github.com/maria.png/",
    ],
    titulo: "MauroCMP usuario de skate",
    descricao: "Usuario de skate ha 8 anos, favTrick: 360flip",
    cor: ["#5D6CAC", "#EDE5D9", "#C25771"],
    tamanho: ["p", "m", "g", "gg"],
    preco: 300,
    categorias: "casacos",
    slug: "produto-1",
    estoque: 15,
  },
  {
    id: "2",
    galeria: [
      "https://github.com/VictorMont03.png",
      "https://github.com/neto18081.png/",
      "https://github.com/victormonteiro.png/",
      "https://github.com/maria.png/",
      "https://github.com/marlonberaldo.png/",
      "https://github.com/neto18081.png/",
      "https://github.com/victormonteiro.png/",
      "https://github.com/maria.png/",
    ],
    titulo: "Victor Funkeiro, heroi do basquetinho",
    descricao: "Usuario de skate ha 8 anos, favTrick: 360flip",
    cor: ["#5D6CAC", "#EDE5D9", "#C25771"],
    tamanho: ["p", "m", "g", "gg"],
    preco: 352,
    categorias: "casacos",
    slug: "produto-2",
    estoque: 7,
  },
  {
    id: "3",
    galeria: [
      "https://github.com/neto18081.png",
      "https://github.com/neto18081.png/",
      "https://github.com/victormonteiro.png/",
      "https://github.com/maria.png/",
      "https://github.com/marlonberaldo.png/",
      "https://github.com/neto18081.png/",
      "https://github.com/victormonteiro.png/",
      "https://github.com/maria.png/",
    ],
    titulo: "Pedrao da Maria, heroi do JavaScript",
    descricao: "Usuario de skate ha 8 anos, favTrick: 360flip",
    cor: ["#5D6CAC", "#EDE5D9", "#C25771"],
    tamanho: ["p", "m", "g", "gg"],
    preco: 352,
    categorias: "casacos",
    slug: "produto-3",
    estoque: 1,
  },
  {
    id: "4",
    galeria: [
      "https://github.com/marlonberaldo.png",
      "https://github.com/neto18081.png/",
      "https://github.com/victormonteiro.png/",
      "https://github.com/maria.png/",
      "https://github.com/marlonberaldo.png/",
      "https://github.com/neto18081.png/",
      "https://github.com/victormonteiro.png/",
      "https://github.com/maria.png/",
    ],
    titulo: "Pedrao da Maria, heroi do JavaScript",
    descricao: "Usuario de skate ha 8 anos, favTrick: 360flip",
    cor: ["#5D6CAC", "#EDE5D9", "#C25771"],
    tamanho: ["p", "m", "g", "gg"],
    preco: 248,
    categorias: "casacos",
    slug: "produto-4",
    estoque: 4,
  },
  {
    id: "5",
    galeria: [
      "https://github.com/marlonberaldo.png",
      "https://github.com/neto18081.png/",
      "https://github.com/victormonteiro.png/",
      "https://github.com/maria.png/",
      "https://github.com/marlonberaldo.png/",
      "https://github.com/neto18081.png/",
      "https://github.com/victormonteiro.png/",
      "https://github.com/maria.png/",
    ],
    titulo: "Pedrao da Maria, heroi do JavaScript",
    descricao: "Usuario de skate ha 8 anos, favTrick: 360flip",
    cor: ["#5D6CAC", "#EDE5D9", "#C25771"],
    tamanho: ["p", "m", "g", "gg"],
    preco: 248,
    categorias: "bermuda",
    slug: "produto-5",
    estoque: 4,
  },
  {
    id: "6",
    galeria: [
      "https://github.com/marlonberaldo.png",
      "https://github.com/neto18081.png/",
      "https://github.com/victormonteiro.png/",
      "https://github.com/maria.png/",
      "https://github.com/marlonberaldo.png/",
      "https://github.com/neto18081.png/",
      "https://github.com/victormonteiro.png/",
      "https://github.com/maria.png/",
    ],
    titulo: "Pedrao da Maria, heroi do JavaScript",
    descricao: "Usuario de skate ha 8 anos, favTrick: 360flip",
    cor: ["#5D6CAC", "#EDE5D9", "#C25771"],
    tamanho: ["p", "m", "g", "gg"],
    preco: 512,
    categorias: "zorba",
    slug: "produto-6",
    estoque: 8,
  },
];

export const Categorias = [
  {
    name: "Casacos",
    slug: "casacos",
  },
  {
    name: "Zorba",
    slug: "zorba",
  },

  {
    name: "Bermuda",
    slug: "bermuda",
  },
];
